// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: decorator/v0/decorator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecorateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []string               `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecorateRequest) Reset() {
	*x = DecorateRequest{}
	mi := &file_decorator_v0_decorator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecorateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecorateRequest) ProtoMessage() {}

func (x *DecorateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decorator_v0_decorator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecorateRequest.ProtoReflect.Descriptor instead.
func (*DecorateRequest) Descriptor() ([]byte, []int) {
	return file_decorator_v0_decorator_proto_rawDescGZIP(), []int{0}
}

func (x *DecorateRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type DecorateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key = member 字符串；value = 不透明展示结构（业务自定义字段，ranking-service 透传）。
	Display       map[string]*structpb.Struct `protobuf:"bytes,1,rep,name=display,proto3" json:"display,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecorateResponse) Reset() {
	*x = DecorateResponse{}
	mi := &file_decorator_v0_decorator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecorateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecorateResponse) ProtoMessage() {}

func (x *DecorateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decorator_v0_decorator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecorateResponse.ProtoReflect.Descriptor instead.
func (*DecorateResponse) Descriptor() ([]byte, []int) {
	return file_decorator_v0_decorator_proto_rawDescGZIP(), []int{1}
}

func (x *DecorateResponse) GetDisplay() map[string]*structpb.Struct {
	if x != nil {
		return x.Display
	}
	return nil
}

var File_decorator_v0_decorator_proto protoreflect.FileDescriptor

const file_decorator_v0_decorator_proto_rawDesc = "" +
	"\n" +
	"\x1cdecorator/v0/decorator.proto\x12\fdecorator.v0\x1a\x1cgoogle/protobuf/struct.proto\"+\n" +
	"\x0fDecorateRequest\x12\x18\n" +
	"\amembers\x18\x01 \x03(\tR\amembers\"\xae\x01\n" +
	"\x10DecorateResponse\x12E\n" +
	"\adisplay\x18\x01 \x03(\v2+.decorator.v0.DecorateResponse.DisplayEntryR\adisplay\x1aS\n" +
	"\fDisplayEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x012V\n" +
	"\tDecorator\x12I\n" +
	"\bDecorate\x12\x1d.decorator.v0.DecorateRequest\x1a\x1e.decorator.v0.DecorateResponseB8Z6github.com/mysunshines/blog-user/proto/decorator/v0/pbb\x06proto3"

var (
	file_decorator_v0_decorator_proto_rawDescOnce sync.Once
	file_decorator_v0_decorator_proto_rawDescData []byte
)

func file_decorator_v0_decorator_proto_rawDescGZIP() []byte {
	file_decorator_v0_decorator_proto_rawDescOnce.Do(func() {
		file_decorator_v0_decorator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_decorator_v0_decorator_proto_rawDesc), len(file_decorator_v0_decorator_proto_rawDesc)))
	})
	return file_decorator_v0_decorator_proto_rawDescData
}

var file_decorator_v0_decorator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_decorator_v0_decorator_proto_goTypes = []any{
	(*DecorateRequest)(nil),  // 0: decorator.v0.DecorateRequest
	(*DecorateResponse)(nil), // 1: decorator.v0.DecorateResponse
	nil,                      // 2: decorator.v0.DecorateResponse.DisplayEntry
	(*structpb.Struct)(nil),  // 3: google.protobuf.Struct
}
var file_decorator_v0_decorator_proto_depIdxs = []int32{
	2, // 0: decorator.v0.DecorateResponse.display:type_name -> decorator.v0.DecorateResponse.DisplayEntry
	3, // 1: decorator.v0.DecorateResponse.DisplayEntry.value:type_name -> google.protobuf.Struct
	0, // 2: decorator.v0.Decorator.Decorate:input_type -> decorator.v0.DecorateRequest
	1, // 3: decorator.v0.Decorator.Decorate:output_type -> decorator.v0.DecorateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_decorator_v0_decorator_proto_init() }
func file_decorator_v0_decorator_proto_init() {
	if File_decorator_v0_decorator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decorator_v0_decorator_proto_rawDesc), len(file_decorator_v0_decorator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decorator_v0_decorator_proto_goTypes,
		DependencyIndexes: file_decorator_v0_decorator_proto_depIdxs,
		MessageInfos:      file_decorator_v0_decorator_proto_msgTypes,
	}.Build()
	File_decorator_v0_decorator_proto = out.File
	file_decorator_v0_decorator_proto_goTypes = nil
	file_decorator_v0_decorator_proto_depIdxs = nil
}
