// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: decorator/v0/decorator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Decorator_Decorate_FullMethodName = "/decorator.v0.Decorator/Decorate"
)

// DecoratorClient is the client API for Decorator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DecoratorClient interface {
	// Decorate 批量将 members 转为展示信息。返回的 map key 必须与入参 member 一致。
	Decorate(ctx context.Context, in *DecorateRequest, opts ...grpc.CallOption) (*DecorateResponse, error)
}

type decoratorClient struct {
	cc grpc.ClientConnInterface
}

func NewDecoratorClient(cc grpc.ClientConnInterface) DecoratorClient {
	return &decoratorClient{cc}
}

func (c *decoratorClient) Decorate(ctx context.Context, in *DecorateRequest, opts ...grpc.CallOption) (*DecorateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecorateResponse)
	err := c.cc.Invoke(ctx, Decorator_Decorate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DecoratorServer is the server API for Decorator service.
// All implementations must embed UnimplementedDecoratorServer
// for forward compatibility.
type DecoratorServer interface {
	// Decorate 批量将 members 转为展示信息。返回的 map key 必须与入参 member 一致。
	Decorate(context.Context, *DecorateRequest) (*DecorateResponse, error)
	mustEmbedUnimplementedDecoratorServer()
}

// UnimplementedDecoratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecoratorServer struct{}

func (UnimplementedDecoratorServer) Decorate(context.Context, *DecorateRequest) (*DecorateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decorate not implemented")
}
func (UnimplementedDecoratorServer) mustEmbedUnimplementedDecoratorServer() {}
func (UnimplementedDecoratorServer) testEmbeddedByValue()                   {}

// UnsafeDecoratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecoratorServer will
// result in compilation errors.
type UnsafeDecoratorServer interface {
	mustEmbedUnimplementedDecoratorServer()
}

func RegisterDecoratorServer(s grpc.ServiceRegistrar, srv DecoratorServer) {
	// If the following call panics, it indicates UnimplementedDecoratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Decorator_ServiceDesc, srv)
}

func _Decorator_Decorate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecorateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecoratorServer).Decorate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Decorator_Decorate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecoratorServer).Decorate(ctx, req.(*DecorateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Decorator_ServiceDesc is the grpc.ServiceDesc for Decorator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Decorator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "decorator.v0.Decorator",
	HandlerType: (*DecoratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decorate",
			Handler:    _Decorator_Decorate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "decorator/v0/decorator.proto",
}
